/*
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ide

import com.google.inject.Guice
import m1ice.pdc.mhw.xtext.MhwDSLRuntimeModule
import m1ice.pdc.mhw.xtext.MhwDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MhwDSLIdeSetup extends MhwDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MhwDSLRuntimeModule, new MhwDSLIdeModule))
	}
	
}
