/*
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMhwDSLScopeProvider extends DelegatingScopeProvider {
}
