/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.scoping;

import m1ice.pdc.mhw.xtext.scoping.AbstractMhwDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MhwDSLScopeProvider extends AbstractMhwDSLScopeProvider {
}
