/*
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ui.tests;

import com.google.inject.Injector;
import m1ice.pdc.mhw.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MhwDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("m1ice.pdc.mhw.xtext.MhwDSL");
	}

}
