/*
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import m1ice.pdc.mhw.xtext.ide.contentassist.antlr.internal.InternalMhwDSLParser;
import m1ice.pdc.mhw.xtext.services.MhwDSLGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MhwDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MhwDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MhwDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getRequestAccess().getGroup(), "rule__Request__Group__0");
			builder.put(grammarAccess.getDecorationAccess().getGroup(), "rule__Decoration__Group__0");
			builder.put(grammarAccess.getCharmAccess().getGroup(), "rule__Charm__Group__0");
			builder.put(grammarAccess.getArmorAccess().getGroup(), "rule__Armor__Group__0");
			builder.put(grammarAccess.getWeaponAccess().getGroup(), "rule__Weapon__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getSkillAccess().getGroup(), "rule__Skill__Group__0");
			builder.put(grammarAccess.getRequestAccess().getNameAssignment_2(), "rule__Request__NameAssignment_2");
			builder.put(grammarAccess.getRequestAccess().getArmorAssignment_3(), "rule__Request__ArmorAssignment_3");
			builder.put(grammarAccess.getRequestAccess().getWeaponAssignment_4(), "rule__Request__WeaponAssignment_4");
			builder.put(grammarAccess.getRequestAccess().getCharmAssignment_5(), "rule__Request__CharmAssignment_5");
			builder.put(grammarAccess.getRequestAccess().getDecorationAssignment_6(), "rule__Request__DecorationAssignment_6");
			builder.put(grammarAccess.getDecorationAccess().getNameAssignment_2(), "rule__Decoration__NameAssignment_2");
			builder.put(grammarAccess.getCharmAccess().getNameAssignment_2(), "rule__Charm__NameAssignment_2");
			builder.put(grammarAccess.getArmorAccess().getNameAssignment_2(), "rule__Armor__NameAssignment_2");
			builder.put(grammarAccess.getWeaponAccess().getNameAssignment_2(), "rule__Weapon__NameAssignment_2");
			builder.put(grammarAccess.getSkillAccess().getSkillNameAssignment_2(), "rule__Skill__SkillNameAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MhwDSLGrammarAccess grammarAccess;

	@Override
	protected InternalMhwDSLParser createParser() {
		InternalMhwDSLParser result = new InternalMhwDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MhwDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MhwDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
