/*
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MhwDSLStandaloneSetup extends MhwDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MhwDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
