/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext;

import m1ice.pdc.mhw.xtext.MhwDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MhwDSLStandaloneSetup extends MhwDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new MhwDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
