/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext;

import m1ice.pdc.mhw.xtext.AbstractMhwDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MhwDSLRuntimeModule extends AbstractMhwDSLRuntimeModule {
}
