/*
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MhwDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("m1ice/pdc/mhw/xtext/parser/antlr/internal/InternalMhwDSL.tokens");
	}
}
