/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ide;

import m1ice.pdc.mhw.xtext.ide.AbstractMhwDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MhwDSLIdeModule extends AbstractMhwDSLIdeModule {
}
