/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import m1ice.pdc.mhw.xtext.MhwDSLRuntimeModule;
import m1ice.pdc.mhw.xtext.MhwDSLStandaloneSetup;
import m1ice.pdc.mhw.xtext.ide.MhwDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MhwDSLIdeSetup extends MhwDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MhwDSLRuntimeModule _mhwDSLRuntimeModule = new MhwDSLRuntimeModule();
    MhwDSLIdeModule _mhwDSLIdeModule = new MhwDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mhwDSLRuntimeModule, _mhwDSLIdeModule));
  }
}
