/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class MhwDSLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
