/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class MhwDSLLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public MhwDSLLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
