/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ui.contentassist;

import m1ice.pdc.mhw.xtext.ui.contentassist.AbstractMhwDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MhwDSLProposalProvider extends AbstractMhwDSLProposalProvider {
}
