/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.ui;

import m1ice.pdc.mhw.xtext.ui.AbstractMhwDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MhwDSLUiModule extends AbstractMhwDSLUiModule {
  public MhwDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
