/**
 * generated by Xtext 2.16.0
 */
package m1ice.pdc.mhw.xtext.validation;

import m1ice.pdc.mhw.xtext.validation.AbstractMhwDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MhwDSLValidator extends AbstractMhwDSLValidator {
}
